export const texts = {
    header: {
      title: "Libro del Aventurero",
      subtitle: "Gestiona tu riqueza y aventuras",
    },
    userMenu: {
      profile: "Perfil",
      settings: "Configuración",
      logout: "Cerrar Sesión",
    },
    card: {
      title: "Cambio de Moneda",
      description: "Convierte entre tipos de moneda de D&D",
      fromCurrency: "Desde Moneda",
      amount: "Cantidad",
      toCurrency: "A Moneda",
      transform: "Transformar",
      enterAmount: "Ingresa cantidad",
      selectCurrency: "Selecciona moneda",
      resultText: (amount: string, fromName: string, fromId: string, result: string, toName: string, toId: string) =>
        `${amount} ${fromName} (${fromId}) equivale a ${result} ${toName} (${toId})`,
    },
    footer: {
      text: "Track your D&D wealth and character progress",
    },
    sidebar: {
      title: "Herramientas D&D",
      welcome: "Inicio",
      currencyConverter: "Conversor de Monedas",
      wallet: "Administrador de Billetera",
      character: "Personaje",
      characters: "Personajes",
      movements: "Movimientos",
      finances: "Finanzas",
      inventory: "Inventario",
      campaigns: "Campañas",
      map: "Mapa",
      marketplace: "Mercado",
      comingSoon: "Más herramientas próximamente...",
    },
    wallet: {
      title: "Gestor de Monedero",
      description: "Gestiona las monedas de tu personaje",
      balance: "Balance Actual",
      addCoins: "Agregar Monedas",
      removeCoins: "Quitar Monedas",
      currency: "Moneda",
      amount: "Cantidad",
      add: "Agregar",
      remove: "Quitar",
      totalWealth: "Riqueza Total",
      totalInGold: "Total en Oro",
      enterAmount: "Ingresa cantidad",
      selectCurrency: "Selecciona moneda",
      success: "Transacción completada exitosamente",
      error: "Cantidad inválida",
      insufficientFunds: "Fondos insuficientes",
      noCharacter: "No se encontró ningún personaje. Por favor, crea un personaje primero.",
      managingWallet: "Gestionando monedero de",
    },
    character: {
      title: "Gestor de Personaje",
      description: "Gestiona la información de tu personaje",
      characterName: "Nombre del Personaje",
      race: "Especie",
      load: "Cargar",
      save: "Guardar",
      enterName: "Ingresa el nombre del personaje",
      enterRace: "Ingresa la especie",
      success: "Personaje guardado exitosamente",
      loaded: "Personaje cargado exitosamente",
      notFound: "Personaje no encontrado",
      error: "Error procesando la solicitud",
      createFirst: "Crea Tu Primer Personaje",
      noCharactersYet: "¡Bienvenido! Vamos a crear tu primer personaje de D&D",
      createFirstInfo:
        "Comienza tu aventura creando un personaje. Podrás gestionar su monedero y usar todas las herramientas.",
      createCharacter: "Crear Personaje",
      updateCharacter: "Actualizar Personaje",
      updated: "Personaje actualizado exitosamente",
      editingCharacter: "Estás editando tu personaje. Realiza cambios y haz clic en Actualizar Personaje para guardar.",
      archive: "Archivar",
      archived: "Archivado",
      archiveConfirm: "¿Archivar este personaje? Puedes restaurarlo más tarde.",
      archiveSuccess: "Personaje archivado exitosamente",
      noActiveCharacters: "No hay personajes activos. ¡Crea uno para comenzar!",
      activeCharacters: "Personajes Activos",
      archivedCharacters: "Personajes Archivados",
      restore: "Restaurar",
      restoreConfirm: "¿Restaurar este personaje?",
      restoreSuccess: "Personaje restaurado con éxito",
      noArchivedCharacters: "No hay personajes archivados",
      archivedAppearHere: "Los personajes archivados aparecerán aquí",
      viewProfile: "Ver Perfil",
      viewSheet: "Ver Hoja",
      edit: "Editar",
      editCharacter: "Editar Personaje",
      actions: "Acciones",
      manageAdventurers: "Gestiona tus aventureros",
      createDescription: "Crea un nuevo personaje para tu aventura",
      updateDescription: "Actualiza la información de tu personaje",
      cancel: "Cancelar",
      class: "Clase",
      selectClass: "Seleccionar clase",
      classes: {
        barbarian: "Bárbaro",
        bard: "Bardo",
        cleric: "Clérigo",
        druid: "Druida",
        fighter: "Guerrero",
        monk: "Monje",
        paladin: "Paladín",
        ranger: "Montaraz",
        rogue: "Pícaro",
        sorcerer: "Hechicero",
        warlock: "Brujo",
        wizard: "Mago",
      },
      // Ability Scores
      abilityScores: "Atributos",
      strength: "Fuerza",
      dexterity: "Destreza",
      constitution: "Constitución",
      intelligence: "Inteligencia",
      wisdom: "Sabiduría",
      charisma: "Carisma",
      modifier: "Modificador",
      // Size
      size: "Tamaño",
      sizeSmall: "Pequeño",
      sizeMedium: "Mediano",
      sizeLarge: "Grande",
      // Carrying Capacity
      carryingCapacity: "Capacidad de Carga",
      currentWeight: "Peso Actual",
      maxCapacity: "Capacidad Máxima",
      capacityStatus: {
        light: "Carga Ligera",
        medium: "Carga Media",
        heavy: "Carga Pesada",
        overloaded: "Sobrecargado",
      },
      lightLoad: "Carga Ligera",
      mediumLoad: "Carga Media",
      poundsShort: "lb",
      status: "Estado",
      // Background
      background: "Trasfondo",
      alignment: "Alineamiento",
      experiencePoints: "Puntos de Experiencia",
      // Sections
      sections: {
        basic: "Información Básica",
        abilityScores: "Atributos",
        background: "Trasfondo",
        notes: "Notas",
      },
      // Gender
      gender: "Género",
      selectGender: "Seleccionar género",
      genderMale: "Masculino",
      genderFemale: "Femenino",
      genderOther: "Otro",
      // Additional fields
      level: "Nivel",
      backToCharacters: "Volver a Personajes",
      // Tabs
      tabs: {
        basicInfo: "Información Básica",
        abilityScores: "Atributos",
        background: "Trasfondo",
        notes: "Notas",
        racialTraits: "Traits Raciales",
      },
      // Validation messages
      validation: {
        nameRequired: "El nombre es requerido",
        raceRequired: "La raza es requerida",
        abilityScoreRange: "El atributo debe estar entre 1 y 30",
        levelRange: "El nivel debe estar entre 1 y 20",
        invalidSize: "El tamaño debe ser: pequeño, mediano o grande",
      },
    },
    currencies: {
      platinum: "Platino",
      gold: "Oro",
      electrum: "Electrum",
      silver: "Plata",
      copper: "Cobre",
    },
    welcome: {
      title: "Inicio",
      characterSummary: "Resumen del Personaje",
      wealthSummary: "Resumen de Riqueza",
      noCharacter: "No hay personaje creado",
      createCharacterPrompt: "¡Crea tu primer personaje para comenzar tu aventura!",
      goToCharacter: "Ir al Gestor de Personajes",
      characterName: "Nombre",
      characterRace: "Especie",
      characterLevel: "Nivel",
      characterClass: "Clase",
      totalWealth: "Riqueza Total",
      coinBreakdown: "Desglose de Monedas",
      quickStats: "Estadísticas Rápidas",
      loading: "Cargando...",
      adventurerDetails: "Detalles de tu aventurero",
      coinCollection: "Tu colección de monedas",
      noWalletData: "No se encontraron datos del monedero. Visita el Gestor de Monedero para inicializarlo.",
    },
    characterSelector: {
      selectCharacter: "Seleccionar Personaje",
      activeCharacter: "Personaje Activo",
      manageCharacters: "Gestionar Personajes",
    },
    movements: {
      title: "Movimientos de Monedas",
      description: "Convierte y rastrea tus intercambios de monedas",
      currentBalance: "Saldo Actual",
      conversionForm: "Conversión de Monedas",
      fromCurrency: "De Moneda",
      amount: "Cantidad a Convertir",
      toCurrency: "A Moneda",
      youWillReceive: "Recibirás",
      convert: "Realizar Conversión",
      history: "Historial de Movimientos",
      noHistory: "No hay movimientos aún. ¡Comienza convirtiendo algunas monedas!",
      date: "Fecha",
      conversion: "Conversión",
      enterAmount: "Ingresa la cantidad",
      selectCurrency: "Selecciona la moneda",
      success: "Conversión completada exitosamente",
      insufficientFunds: "Fondos insuficientes para esta conversión",
      invalidAmount: "Por favor, ingresa una cantidad válida",
      sameConversion: "No se puede convertir a la misma moneda",
      noCharacter: "No se encontró ningún personaje. Por favor, crea un personaje primero.",
      recentMovements: "Movimientos Recientes",
      viewAll: "Ver Todos los Movimientos",
    },
    finances: {
      title: "Finanzas del Personaje",
      description: "Gestiona tu riqueza, conversiones y transferencias",
      balanceTab: "Balance",
      transactionsTab: "Transacciones",
      transfersTab: "Transferencias",
      historyTab: "Historial",
      conversionTitle: "Conversión de Monedas",
      conversionDescription: "Convierte entre diferentes tipos de moneda",
      sendMoney: "Enviar Dinero",
      transferDescription: "Transferir monedas al personaje de otro jugador",
      recipient: "Personaje Destinatario",
      selectRecipient: "Seleccionar destinatario",
      note: "Nota",
      noteOptional: "Adicionar una nota (opcional)",
      sendTransfer: "Enviar Transferencia",
      transferHistory: "Historial de Transferencias",
      noTransfers: "No hay transferencias aún",
      sentTo: "Enviado a",
      receivedFrom: "Recibido de",
      transferSuccess: "Transferencia completada exitosamente",
      insufficientFunds: "Fondos insuficientes para esta transferencia",
      invalidAmount: "Por favor, ingresa una cantidad válida",
      cannotTransferSelf: "No puedes transferirte a ti mismo",
      recipientNotFound: "Monedero del destinatario no encontrado",
    },
    characterProfile: {
      title: "Perfil del Personaje",
      description: "Gestiona la información y estadísticas de tu personaje",
      loading: "Cargando personaje...",
      noCharacter: "Sin Personaje Activo",
      createFirst: "Por favor crea o selecciona un personaje primero.",
      updateSuccess: "Personaje actualizado exitosamente",
      updateError: "Error al actualizar personaje",
      updateCharacter: "Actualizar Personaje",
      characterDetails: "Detalles del Personaje",
      narrativeTitle: "Historia del Personaje",
      tabs: {
        profile: "Perfil",
        attributes: "Atributos",
        stats: "Estatísticas",
        narrative: "Narrativa",
      },
      basicInfo: "Información Básica",
      basicInfoDesc: "Detalles principales de tu personaje",
      name: "Nombre",
      race: "Especie",
      class: "Clase",
      level: "Nivel",
      alignment: "Alineación",
      background: "Antecedentes",
      experiencePoints: "Puntos de Experiencia",
      selectClass: "Selecciona una clase",
      selectAlignment: "Selecciona alineación",
      backgroundPlaceholder: "ex., Soldado, Noble, Criminoso",
      classes: [
        "Bárbaro",
        "Bardo",
        "Clérigo",
        "Druida",
        "Guerrero",
        "Monje",
        "Paladín",
        "Guardabosques",
        "Pícaro",
        "Hechicero",
        "Brujo",
        "Mago",
      ],
      alignments: [
        "Leal y Bueno",
        "Neutral y Bueno",
        "Caótico y Bueno",
        "Leal y Neutro",
        "Neutro Verdadero",
        "Caótico y Neutro",
        "Leal y Mau",
        "Neutral y Mau",
        "Caótico y Mau",
      ],
      coreAttributes: "Atributos Principales",
      coreAttributesDesc: "Los seis valores de habilidad que definen tu personaje",
      attributes: {
        strength: "Fuerza",
        dexterity: "Destreza",
        constitution: "Constitución",
        intelligence: "Inteligencia",
        wisdom: "Sabiduría",
        charisma: "Carisma",
      },
      modifier: "Modificador",
      combatStats: "Estadísticas de Combate",
      combatStatsDesc: "Estadísticas relacionadas con el combate",
      potionEffects: "Efectos de Poción",
      spellInformation: "Información del Hechizo",
      wondrousItemDetails: "Detalles del Objeto Maravilloso",
      itemEffects: "Efectos del Item",
      maxHitPoints: "Puntos de Vida Máximos",
      currentHitPoints: "Puntos de Vida Actuales",
      armorClass: "Clase de Armadura (CA)",
      speed: "Velocidad (ft)",
      initiativeBonus: "Bonus de Iniciativa",
      narrativeInfo: "Información Narrativa",
      narrativeInfoDesc: "Describe la apariencia y la historia de tu personaje",
      physicalDescription: "Descripción Física",
      personalityTraits: "Traços de Personalidad",
      backstory: "Historia",
      physicalPlaceholder: "Describe la apariencia de tu personaje...",
      personalityPlaceholder: "Describe la personalidad de tu personaje...",
      backstoryPlaceholder: "Cuénta la historia de tu personaje...",
      backToList: "Volver a la Lista",
    },
    inventory: {
      title: "Inventario",
      description: "Gestiona los objetos y equipamiento de tu personaje",
      noCharacterSelected: "No hay personaje seleccionado. Selecciona un personaje desde el encabezado.",
      tabs: {
        items: "Objetos",
        add: "Añadir",
        equipped: "Equipado",
        summary: "Resumen",
      },
      loading: "Cargando inventario...",
      noItems: "No hay objetos en el inventario. ¡Añade tu primer objeto!",
      itemName: "Nombre del Objeto",
      type: "Tipo",
      quantity: "Cantidad",
      weight: "Peso",
      value: "Valor",
      equipped: "Equipado",
      actions: "Acciones",
      yes: "Sí",
      no: "No",
      itemNamePlaceholder: "Ingresa el nombre del objeto",
      weightLabel: "Peso (lb)",
      valueInCopper: "Valor (piezas de cobre)",
      goldPieces: "piezas de oro",
      equippedLabel: "Equipado",
      descriptionPlaceholder: "Descripción del objeto (opcional)",
      addItem: "Añadir Objeto",
      updateItem: "Actualizar Objeto",
      editingItem: "Editando objeto",
      cancelEdit: "Cancelar Edición",
      itemNameRequired: "El nombre del objeto es requerido",
      invalidValues: "Valores inválidos. Verifica cantidad, peso y valor.",
      success: "Éxito",
      error: "Error",
      itemAdded: "Objeto añadido exitosamente",
      itemUpdated: "Objeto actualizado exitosamente",
      itemDeleted: "Objeto eliminado exitosamente",
      saveError: "Error al guardar el objeto",
      deleteError: "Error al eliminar el objeto",
      loadError: "Error al cargar el inventario",
      noEquippedItems: "No hay objetos equipados",
      unequip: "Desequipar",
      totalItems: "Total de Objetos",
      equippedCount: "equipados",
      totalWeight: "Peso Total",
      pounds: "libras",
      totalValue: "Valor Total",
      itemsByType: "Objetos por Tipo",
      types: {
        weapon: "Arma",
        armor: "Armadura",
        equipment: "Equipamiento",
        consumable: "Consumible",
        treasure: "Tesoro",
        other: "Otro",
      },
      slots: {
        head: {
          name: "Cabeza",
          description: "Diademas, coronas, sombreros, cintas, cascos, filacterias",
        },
        neck: {
          name: "Cuello",
          description:
            "Amuletos, insignias, broches, collares, medallas, medallones, colgantes, periapts, escarabeos, bufandas, torques",
        },
        shoulders: {
          name: "Hombros",
          description: "Capas, mantos, chales",
        },
        body: {
          name: "Cuerpo",
          description: "Armaduras, túnicas",
        },
        hands: {
          name: "Manos",
          description: "Guanteletes, guantes",
        },
        waist: {
          name: "Cintura",
          description: "Cinturones, fajas",
        },
        ringLeft: {
          name: "Anillo (Izquierdo)",
          description: "Anillos mágicos",
        },
        ringRight: {
          name: "Anillo (Derecho)",
          description: "Anillos mágicos",
        },
        feet: {
          name: "Pies",
          description: "Botas, sandalias, zapatos, pantuflas",
        },
        weaponMain: {
          name: "Mano Principal",
          description: "Arma primaria o escudo",
        },
        weaponOff: {
          name: "Mano Secundaria",
          description: "Arma secundaria o escudo",
        },
        backpack: {
          name: "Mochila",
          description: "Contenedor principal llevado en la espalda",
        },
        pouchLeft: {
          name: "Bolso Izquierdo",
          description: "Contenedor pequeño para acceso rápido",
        },
        pouchRight: {
          name: "Bolso Derecho",
          description: "Contenedor pequeño para acceso rápido",
        },
      },
      weaponsTitle: "Armas y Escudos",
      containerSlotsTitle: "Contenedores Equipados",
      storeIn: "Guardar en...",
      storeInContainer: "Guardar en Contenedor",
      selectContainer: "Selecciona contenedor para guardar el objeto",
      noEquippedContainers: "No hay contenedores equipados. Equipa una mochila o bolso primero.",
      capacityExceeded: "Excede la capacidad del contenedor",
      currentLoad: "Carga actual",
      availableCapacity: "Disponible",
      itemStored: "Objeto guardado exitosamente",
      removeFromContainer: "Sacar del contenedor",
      itemRemovedFromContainer: "Objeto sacado del contenedor",
      containerType: "Contenedor",
      isContainer: "Es un contenedor",
      containerCapacity: "Capacidad del contenedor (lb)",
      failedToSave: "Error al guardar el objeto",
      containersTitle: "Contenedores y Mochilas",
      noContainers: "No hay contenedores en el inventario",
      emptyContainer: "Contenedor vacío",
      emptySlot: "Ranura vacía",
      equipItem: "Equipar Objeto",
      selectItemToEquip: "Selecciona el Objeto a Equipar",
      equipToSlot: "Equipando en ranura",
      noAvailableItems: "No hay objetos disponibles para equipar",
      cancel: "Cancelar",
      itemEquipped: "Objeto equipado exitosamente",
      itemUnequipped: "Objeto desequipado exitosamente",
      equipError: "Error al equipar el objeto",
      equippableSlot: "Ranura Equipable",
      selectSlot: "Selecciona ranura equipable",
      descriptionLabel: "Descripción",
    },
    marketplace: {
      locations: "Ubicaciones",
      locationsDescription: "Explora pueblos y aldeas",
      createLocation: "Crear Ubicación",
      locationName: "Nombre de la Ubicación",
      locationSubtitle: "Añade una nueva ubicación a tu campaña",
      enterLocationName: "Ingresa el nombre de la ubicación",
      describeLocation: "Describe esta ubicación",
      shops: "Tiendas",
      shopsDescription: "Explora tiendas en esta ubicación",
      createShop: "Crear Tienda",
      shopName: "Nombre de la Tienda",
      shopSubtitle: "Añade una nueva tienda a esta ubicación",
      enterShopName: "Ingresa el nombre de la tienda",
      shopkeeperName: "Nombre del Tendero",
      enterShopkeeperName: "Ingresa el nombre del tendero",
      describeShop: "Describe esta tienda",
      catalog: "Catálogo de la Tienda",
      catalogDescription: "Explora y compra artículos",
      buy: "Comprar",
      purchaseItem: "Comprar Artículo",
      quantity: "Cantidad",
      pricePerUnit: "Precio por unidad",
      totalPrice: "Precio Total",
      confirmPurchase: "Confirmar Compra",
      mapDescription: "Visualiza campañas, crea ubicaciones y asigna tiendas.",
      noCampaigns: "Únete a una campaña para explorar el mapa.",
      selectCampaign: "Selecciona una campaña",
      yourLocations: "Ubicaciones",
      locationsTag: "lugares",
      emptyLocations: "Aún no hay ubicaciones.",
      noLocationSelected: "Selecciona primero una ubicación.",
      emptyShops: "Sin tiendas definidas aún.",
      shopkeeper: "Encargado",
      npcTitle: "NPCs disponibles",
      npcHint: "Los NPC son opcionales; las tiendas igual pueden funcionar.",
      addNpc: "Agregar NPC",
      emptyNpcs: "No hay NPCs aún.",
      noShopSelected: "Selecciona una tienda para ver detalles.",
      locationType: "Tipo de ubicación",
      selectLocationType: "Selecciona tipo de ubicación",
      shopType: "Tipo de tienda",
      selectShopType: "Selecciona tipo de tienda",
      npcSubtitle: "Describe quién maneja la tienda.",
      npcName: "Nombr del NPC",
      npcTitleField: "Título del NPC",
      npcResistances: "Resistencias",
      npcStory: "Historia",
      editNpc: "Editar NPC",
      saveChanges: "Guardar cambios",
      locationTypes: {
        village: "Pueblo",
        forest: "Bosque",
        camp: "Campamento",
        port: "Puerto",
        ruins: "Ruinas",
        city: "Ciudad",
      },
      shopTypes: {
        inn: "Posada",
        general: "Tienda general",
        smith: "Herrería",
        jewelry: "Joyería",
        market: "Mercado",
        atelier: "Taller",
      },
      manageItems: "Gestionar Items",
      manageItemsDescription: "Gestiona los items disponibles en esta tienda",
      addItem: "Agregar Item",
      editItem: "Editar Item",
      deleteItem: "Eliminar Item",
      updateItem: "Actualizar Item",
      itemDetails: "Detalles del Item",
      creationMethod: "Método de Creación",
      chooseCreationMethod: "Elige cómo agregar el item",
      manualCreation: "Manual",
      aiGeneration: "Generación con IA",
      apiImport: "Importar desde API",
      itemName: "Nombre del Item",
      itemCategory: "Categoría",
      rarity: "Rareza",
      imageUrl: "URL de Imagen",
      damageDice: "Dados de Daño",
      damageType: "Tipo de Daño",
      armorClass: "Clase de Armadura",
      properties: "Propiedades",
      requirements: "Requisitos",
      attunement: "Requiere Sintonización",
      rarities: {
        common: "Común",
        uncommon: "Poco Común",
        rare: "Raro",
        very_rare: "Muy Raro",
        legendary: "Legendario",
        artifact: "Artefacto",
      },
      aiProvider: "Proveedor de IA",
      translationProvider: "Proveedor de Traducción",
      aiPrompt: "Describe el item que quieres crear",
      aiMode: "Modo IA",
      generateNew: "Generar Nuevo Item",
      searchOfficial: "Buscar Item Oficial",
      generating: "Generando...",
      regenerate: "Regenerar",
      useThisItem: "Usar Este Item",
      selectApi: "Seleccionar API",
      searchItems: "Buscar Items",
      allCategories: "Todas las categorías",
      allRarities: "Todas las rarezas",
      itemsAvailable: "items disponibles",
      itemsShown: "mostrados",
      loadingItems: "Cargando items...",
      clearFilters: "Limpiar filtros",
      importing: "Importando...",
      categories: {
        weapon: "Armas",
        armor: "Armaduras",
        potion: "Pociones",
        scroll: "Pergaminos",
        wondrous: "Objetos Maravillosos",
        tool: "Herramientas",
        gear: "Equipo",
        other: "Otros",
      },
      edition: "Edición/Sourcebook",
      allEditions: "Todas las ediciones",
      rarityFilterNote: "Filtro de rareza disponible después de importar",
      searchFirst: "Busca items primero para activar los filtros",
      searchHint: "Ingresa un término de búsqueda y presiona Enter o haz clic en Buscar",
      searchPrompt: "Ingresa un término de búsqueda para encontrar items",
      searchToFindItems: "Busca items para comenzar",
      searchDescription: "Ingresa el nombre de un item en el campo de búsqueda arriba",
      itemsFound: "items encontrados",
      searching: "Buscando...",
      noResultsWithFilters: "No se encontraron items con los filtros aplicados.",
      sortBy: "Ordenar por",
      sortNameAsc: "Nombre (A-Z)",
      sortNameDesc: "Nombre (Z-A)",
      clearSearch: "Limpiar búsqueda",
      realTimeSearchHint: "La búsqueda se realiza automáticamente mientras escribes",
      searchResults: "Resultados de Búsqueda",
      importItem: "Importar Este Item",
      translating: "Importando y traduciendo...",
      noResultsFound: "No se encontraron items. Intenta con otro término.",
      itemCreated: "Item creado exitosamente",
      itemUpdated: "Item actualizado exitosamente",
      itemDeleted: "Item eliminado exitosamente",
      confirmDeleteItem: "¿Estás seguro de que quieres eliminar este item?",
      noItemsYet: "No hay items aún",
      saving: "Guardando...",
      priceAndStock: "Precio y Stock",
      // New effect fields
      wondrousType: "Tipo de Objeto Maravilloso",
      effectDice: "Dados de Efecto",
      effectType: "Tipo de Efecto",
      effectTarget: "Objetivo del Efecto",
      spellLevel: "Nivel de Hechizo",
      spellName: "Nombre del Hechizo",
      spellSchool: "Escuela de Magia",
      effectDescription: "Descripción del Efecto",
      equippableSlot: "Slot Equipable",
      wondrousTypes: {
        ring: "Anillo",
        amulet: "Amuleto",
        necklace: "Collar",
        cloak: "Capa",
        boots: "Botas",
        belt: "Cinturón",
        gloves: "Guantes",
        helmet: "Casco/Yelmo",
        other: "Otro",
      },
      effectTypes: {
        healing: "Curación",
        temporary_hit_points: "Puntos de Golpe Temporales",
        stat_buff: "Mejora de Atributo",
        damage: "Daño",
        condition_removal: "Remover Condición",
        other: "Otro",
      },
      effectTargets: {
        self: "Uno mismo",
        other: "Otro objetivo",
        area: "Área",
      },
      spellSchools: {
        abjuration: "Abjuración",
        conjuration: "Conjuración",
        divination: "Adivinación",
        enchantment: "Encantamiento",
        evocation: "Evocación",
        illusion: "Ilusión",
        necromancy: "Nigromancia",
        transmutation: "Transmutación",
      },
      weaponProperties: {
        finesse: "Sutil",
        versatile: "Versátil",
        light: "Liviana",
        heavy: "Pesada",
        "two-handed": "A dos manos",
        ranged: "A distancia",
        thrown: "Arrojadiza",
        ammunition: "Munición",
        loading: "Recarga",
        reach: "Alcance",
        special: "Especial",
      },
      mapTitle: "Mapa",
      description: "Descripción",
      create: "Crear",
      // Shopping Cart
      cart: "Carrito de Compras",
      cartEmpty: "Tu carrito está vacío",
      addToCart: "Agregar al Carrito",
      adding: "Agregando...",
      item: "artículo",
      items: "artículos",
      stock: "Stock",
      subtotal: "Subtotal",
      checkout: "Finalizar Compra",
      confirmCheckout: "Confirmar Compra",
      checkoutConfirmation: "¿Estás seguro de que quieres comprar estos artículos?",
      checkoutWarning: "Esto deducirá dinero de tu billetera y agregará artículos a tu inventario.",
      cancel: "Cancelar",
      processing: "Procesando...",
      viewItems: "Ver Artículos",
      purchaseSuccessful: "Compra Exitosa",
      purchaseSummary: "Resumen de Compra",
      totalDeducted: "Total Descontado",
      viewInventory: "Ver Inventario",
      continueShopping: "Seguir Comprando",
      itemsAddedToInventory: "Los artículos han sido agregados a tu inventario",
      insufficientFunds: "Fondos Insuficientes",
      insufficientFundsDescription: "No tienes suficiente dinero para completar esta compra.",
      currentBalance: "Balance Actual",
      totalNeeded: "Total Necesario",
      difference: "Faltante",
      walletBreakdown: "Desglose de tu Billetera",
      insufficientFundsSuggestion: "Puedes remover algunos artículos del carrito o agregar fondos a tu billetera para completar la compra.",
      goToWallet: "Ir a Billetera",
      availableBalance: "Balance Disponible",
      insufficientFundsWarning: "Faltan {amount} para completar esta compra.",
    },
    auth: {
      title: "Autenticación",
      email: "Correo Electrónico",
      password: "Contraseña",
      login: "Iniciar Sesión",
      loginDescription: "Accede a la cuenta de tu aventurero",
      signUp: "Crear Cuenta",
      signUpDescription: "Crea una nueva cuenta de aventurero",
      signUpWithGoogle: "Crear cuenta con Google",
      loginWithGoogle: "Iniciar sesión con Google",
      displayName: "Nombre de Pantalla",
      displayNamePlaceholder: "Tu nombre de aventurero",
      emailPlaceholder: "tu@correo.com",
      repeatPassword: "Repetir Contraseña",
      passwordMismatch: "Las contraseñas no coinciden",
      logoutConfirm: "¿Estás seguro que quieres cerrar sesión?",
      logout: "Cerrar Sesión",
      creatingAccount: "Creando cuenta...",
      signUpError: "Fallo al crear cuenta",
      loginError: "Fallo al iniciar sesión",
      orContinueWith: "O continúa con",
      haveAccount: "¿Ya tienes cuenta?",
      noAccount: "¿No tienes cuenta?",
    },
    settings: {
      languagePreferences: "Preferencias de Idioma",
      chooseLanguage: "Elige tu idioma preferido para la interfaz",
      interfaceLanguage: "Idioma de la Interfaz",
      additionalSettings: "Configuración Adicional",
      comingSoon: "Más opciones de personalización próximamente",
      futureSettings:
        "Configuraciones futuras como preferencias de tema, notificaciones y valores predeterminados de campaña aparecerán aquí.",
    },
    profile: {
      title: "Perfil de Usuario",
      userInformation: "Información de Usuario",
      userDetails: "Información de tu cuenta",
      displayName: "Nombre de Pantalla",
      email: "Dirección de Correo",
      joinedDate: "Fecha de Registro",
      accountProvider: "Proveedor de Cuenta",
      emailPassword: "Correo y Contraseña",
      security: "Seguridad",
      passwordSettings: "Configuración de contraseña y seguridad de la cuenta",
      changePassword: "Cambiar Contraseña",
      currentPassword: "Contraseña Actual",
      newPassword: "Nueva Contraseña",
      confirmNewPassword: "Confirmar Nueva Contraseña",
      updatePassword: "Actualizar Contraseña",
      passwordUpdated: "Contraseña actualizada exitosamente",
      passwordError: "Error al actualizar la contraseña",
      passwordMismatch: "Las nuevas contraseñas no coinciden",
      googleAccount: "Cuenta de Google",
      googleAccountNote:
        "Tu cuenta está vinculada con Google. Los cambios de contraseña se gestionan a través de tu cuenta de Google.",
    },
    campaigns: {
      title: "Campañas",
      subtitle: "Gestiona tus campañas de D&D",
      loading: "Cargando campañas...",
      createCampaign: "Crear Campaña",
      joinCampaign: "Unirse a Campaña",
      allCampaigns: "Todas las Campañas",
      asGM: "Como GM",
      asPlayer: "Como Jugador",
      campaignsAsGM: "Campañas como Game Master",
      campaignsAsPlayer: "Campañas como Player",
      noCampaigns: "No hay campañas aún. ¡Crea una para comenzar!",
      campaignName: "Nombre de la Campaña",
      description: "Descripción",
      namePlaceholder: "Ingresa el nombre de la campaña",
      descriptionPlaceholder: "Describe tu campaña",
      create: "Crear",
      join: "Unirse",
      inviteCode: "Código de Invitación",
      invalidInviteCode: "Código de invitación inválido",
      alreadyMember: "Ya eres miembro de esta campaña",
      campaignCreated: "¡Campaña creada exitosamente!",
      joinedCampaign: "¡Te uniste a la campaña exitosamente!",
      inviteCodeCopied: "¡Código de invitación copiado!",
      noDescription: "Sin descripción",
      player: "Jugador",
      members: "Miembros",
      confirmLeave: "¿Estás seguro que quieres salir de esta campaña?",
      confirmDelete: "¿Estás seguro que quieres eliminar esta campaña?",
      leftCampaign: "Saliste de la campaña exitosamente",
      campaignDeleted: "Campaña eliminada exitosamente",
      deleteCampaign: "Eliminar Campaña",
      leaveCampaign: "Salir de Campaña",
      createDescription: "Crea una nueva campaña e invita jugadores",
      joinDescription: "Ingresa el código de invitación para unirte a una campaña",
      myCampaigns: "Mis Campañas",
      availableCampaigns: "Campañas Disponibles",
      createdBy: "Creada por",
      createCharacterFirst: "Crea un personaje primero para ver campañas disponibles.",
      gameMaster: "Game Master",
      pendingInvitations: "Invitaciones Pendientes",
      invitationsDescription: "Tienes invitaciones de campaña pendientes",
      invitation: "Invitación",
      invitedBy: "Invitado por",
      accept: "Aceptar",
      reject: "Rechazar",
      invitePlayer: "Invitar Jugador",
      invitePlayerDescription: "Ingresa el correo electrónico del usuario que quieres invitar a esta campaña",
      invitePlayerHint: "Envía una invitación por correo electrónico para agregar jugadores a esta campaña",
      email: "Correo Electrónico",
      emailPlaceholder: "Ingresa correo electrónico",
      inviteEmailDescription: "Ingresa el correo electrónico del usuario que quieres invitar",
      invalidEmail: "Formato de correo inválido",
      message: "Mensaje (Opcional)",
      messagePlaceholder: "Agrega un mensaje personal...",
      sendInvitation: "Enviar Invitación",
      invitationSent: "¡Invitación enviada exitosamente!",
      invitationAccepted: "¡Invitación aceptada! Ahora eres miembro.",
      invitationRejected: "Invitación rechazada",
      invitationError: "Error al procesar la invitación",
      invitationNotFound: "Invitación no encontrada o ya procesada",
      userNotFound: "Usuario no encontrado",
      cannotInviteYourself: "No puedes invitarte a ti mismo",
      userAlreadyMember: "El usuario ya es miembro de esta campaña",
      invitationAlreadySent: "Ya se envió una invitación a este usuario",
      searchError: "Error al buscar usuarios",
      removeMember: "Eliminar miembro",
      confirmRemoveMember: "¿Estás seguro que quieres eliminar a {name} de esta campaña?",
      memberRemoved: "Miembro eliminado exitosamente",
      errorRemovingMember: "Error al eliminar miembro",
      noMembers: "No hay miembros en esta campaña",
      overview: "Resumen",
      filteredByCharacter: "Filtrado por personaje activo",
      selectCharacterToView: "Por favor selecciona un personaje para ver sus campañas",
      selectCharacterFirst: "Por favor selecciona un personaje primero para unirte a la campaña",
    },
} as const