/**
 * Códigos de error estandarizados para la aplicación
 * Cada código representa un tipo específico de error que puede ocurrir
 */
export enum ErrorCode {
  // Wallet errors
  WALLET_NOT_FOUND = "WALLET_NOT_FOUND",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",

  // Character errors
  CHARACTER_NOT_FOUND = "CHARACTER_NOT_FOUND",
  CHARACTER_ACCESS_DENIED = "CHARACTER_ACCESS_DENIED",

  // Inventory errors
  ITEM_NOT_FOUND = "ITEM_NOT_FOUND",
  INSUFFICIENT_QUANTITY = "INSUFFICIENT_QUANTITY",
  ITEM_ALREADY_EQUIPPED = "ITEM_ALREADY_EQUIPPED",
  INVALID_EQUIPMENT_SLOT = "INVALID_EQUIPMENT_SLOT",

  // Campaign errors
  CAMPAIGN_NOT_FOUND = "CAMPAIGN_NOT_FOUND",
  CAMPAIGN_ACCESS_DENIED = "CAMPAIGN_ACCESS_DENIED",
  CAMPAIGN_ALREADY_JOINED = "CAMPAIGN_ALREADY_JOINED",

  // Shop errors
  SHOP_NOT_FOUND = "SHOP_NOT_FOUND",
  INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",
  ITEM_NOT_AVAILABLE = "ITEM_NOT_AVAILABLE",

  // Shopping Cart errors
  CART_NOT_FOUND = "CART_NOT_FOUND",
  CART_EMPTY = "CART_EMPTY",
  CHECKOUT_FAILED = "CHECKOUT_FAILED",

  // Transfer errors
  TRANSFER_FAILED = "TRANSFER_FAILED",
  INVALID_TRANSFER_AMOUNT = "INVALID_TRANSFER_AMOUNT",

  // Generic errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

